#define BOTH_SHIFTS_TURNS_ON_CAPS_WORD

#ifdef TAPPING_TERM
#  undef TAPPING_TERM
#endif // !TAPPING_TERM

#define TAPPING_TERM 200

#define IGNORE_MOD_TAP_INTERRUPT

#define LED_NUM_LOCK_PIN B0
#define LED_CAPS_LOCK_PIN B1
#define LED_SCROLL_LOCK_PIN B2
#define LED_COMPOSE_PIN B3
#define LED_KANA_PIN B4
